version: '2'

services:
  app:
    image: 'bmichalski/satis-app'
    environment:
      - 'COMPOSER_GITHUB_OAUTH_TOKEN'
      - 'GITHUB_WEBHOOK_SECRET_TOKEN'
    volumes:
      - 'satis-web:/home/satis/app/web'
      - '/home/satis/.composer/cache'
      - '${SATIS_JSON_FILE}:/home/satis/conf/satis.json'
    depends_on:
      - 'gearman'
  nginx:
    image: 'bmichalski/satis-nginx'
    volumes:
      - 'satis-web:/home/satis/app/web'
    ports:
      - ${SATIS_PORT}:8080
      - ${SATIS_BUILD_PORT}:8081
  gearman:
    image: 'bmichalski/satis-gearman'

volumes:
  satis-web:
