version: '2'

services:
  app:
    image: 'bmichalski/satis-app'
    environment:
      - 'ID_RSA_FILE'
      - 'ID_RSA_PUB_FILE'
      - 'COMPOSER_GITHUB_OAUTH_TOKEN'
      - 'GITHUB_WEBHOOK_SECRET_TOKEN'
    volumes:
      - 'satis-web:/home/satis/app/web'
      - '/home/satis/.composer/cache'
      - './conf:/home/satis/conf:ro'
      - '${ID_RSA_FILE}:/home/satis/.ssh/id_rsa:ro'
      - '${ID_RSA_PUB_FILE}:/home/satis/.ssh/id_rsa.pub:ro'
    depends_on:
      - 'gearman'
  nginx:
    image: 'bmichalski/satis-nginx'
    volumes:
      - 'satis-web:/home/satis/app/web'
    ports:
      - 80:80
  gearman:
    image: 'bmichalski/satis-gearman'

volumes:
  satis-web:
